### ISSUE TITLE
在手机上打开，无法返回结果

### ISSUE THREAD

**Issue by torome** [sumingcheng/Vue3-TS-ChatGPT#4]
在电脑端，不管是chrome还是firefox下，都可以正常，切换到手机模式下也正常，但是在真实手机打开就有问题，没有返回结果，卡在那边
const reader = data.getReader()
    await readStream(reader)
这两句没有执行，会不会是兼容的问题

**Comment by sumingcheng** [comment]
只要挂的梯子没问题，都是可以正常使用的。
但是不推荐手机使用，我暂时没对手机的界面进行优化。
手机端推荐搞个机器人，用起来方便。
可以看看这个[https://aircode.cool/q4y1msdim4](url)

**Comment by torome** [comment]
我是弄了代理服务器转发的，不需要梯子，网页端都是正常的，在手机上打开就是有问题，同一份代码，不应该呀。

**Comment by sumingcheng** [comment]
![ced4a2013a6473c6c9cde5d97f33171](https://github.com/sumingcheng/Vue3-TS-ChatGPT/assets/21992204/58f4e7a6-7da5-42a5-9955-227dc703dbb9)
我这边是可以的，可能是你忘记填sk了

**Comment by torome** [comment]
我刚才用安卓手机试了下，又可以正常，然后我自己的IOS手机，一直都不行
![b115029fcc47ad0356a6a64d8936833](https://github.com/sumingcheng/Vue3-TS-ChatGPT/assets/284013/93463985-ea49-4781-9353-b3e0671af1ab)
![f45ce7211e1ec44fceb5ae5eb316d85](https://github.com/sumingcheng/Vue3-TS-ChatGPT/assets/284013/6aad56a2-a777-4554-8eef-fb6d6f0fd8d7)

**Comment by torome** [comment]
请问有尝试在ios手机上面正常吗？

**Comment by sumingcheng** [comment]
抱歉哈，😂没有IOS的手机

**Comment by torome** [comment]
好的，那我尝试下其他方案，非常感谢

**Comment by sumingcheng** [comment]
问题已修复，昨天用同事手机试了下，确实不可以。
![image](https://github.com/sumingcheng/Vue3-TS-ChatGPT/assets/21992204/9af84041-fbb5-42ce-b5bb-80e2f18aa338)
